import { Track } from '../../types';

export const newTracks: Track[] = [
  {
    id: 'jax', slug: 'jax', title: 'JAX for ML Engineering', description: 'Build differentiable, accelerated numerical programs with JAX and measure their performance correctly.', iconName: 'Cpu', level: 'Intermediate', accentColor: 'from-cyan-500 to-blue-500',
    modules: [{ id: 'jax-foundations', trackId: 'jax', title: 'Transformations & Training', description: 'From array operations to a compiled gradient step.', lessons: [{
      id: 'jax-transformations', moduleId: 'jax-foundations', trackId: 'jax', title: 'JAX: grad, jit and vmap in Practice', durationMinutes: 35, difficulty: 'Intermediate', prerequisites: ['Python', 'NumPy', 'Basic calculus'],
      learningObjectives: ['Compose differentiation, compilation and batching.', 'Write a pure loss function and take a gradient step.', 'Separate compilation overhead from steady-state runtime.'],
      overview: 'JAX combines NumPy-style arrays with program transformations for machine learning and scientific computing. Start with pure functions, then transform them into gradients, compiled programs or batches.',
      theory: '### A transformation-first workflow\n\nWrite a function whose result depends only on its arguments. grad differentiates a scalar-valued function; jit compiles compatible computations; vmap maps a function across a batch dimension. Compose these transformations rather than maintaining separate loop implementations.\n\n### Tracing and shapes\n\nJIT traces computations using abstract values. Python side effects and data-dependent Python branches do not behave like ordinary eager execution. Keep array shapes predictable, use JAX control-flow primitives when needed, and expect recompilation when shapes or static arguments change.\n\n### Practice\n\nRun the example, print the initial and updated losses, then batch predictions with vmap. Warm up the compiled function before timing it and call block_until_ready on results to include asynchronous device execution. Compare correctness before comparing speed.\n\n### Randomness\n\nPass random keys explicitly and split them before independent random operations. Reusing a key repeats its random values. Check the official installation guide for your CPU, GPU or TPU environment.',
      codeSnippet: { title: 'A compiled gradient step', language: 'python', code: 'import jax\nimport jax.numpy as jnp\n\nx = jnp.array([1., 2., 3.])\ny = 2 * x\n\ndef loss(w, x, y):\n    return jnp.mean((w * x - y) ** 2)\n\n@jax.jit\ndef step(w, x, y):\n    return w - 0.05 * jax.grad(loss)(w, x, y)\n\nw = jnp.array(0.)\nupdated = step(w, x, y)\nupdated.block_until_ready()\nprint(loss(w, x, y), loss(updated, x, y))\npredict = jax.vmap(lambda value: updated * value)\nprint(predict(x))' },
      tradeoffs: ['Compilation overhead can dominate small or one-off workloads.', 'Stable shapes improve compilation reuse; dynamic workloads need care.'], commonMistakes: ['Timing asynchronous dispatch without waiting for results.', 'Mutating Python state inside a transformed function.', 'Reusing random keys unintentionally.'],
      interviewQuestions: [{ question: 'Why can the first JIT call be slower?', answer: 'The first call includes tracing and compilation. Benchmark warmed-up calls with matching shapes, and wait for device work to complete.' }],
      quiz: [{ id: 'jax-q1', question: 'What should you do when benchmarking a compiled JAX step?', options: ['Time only the first call', 'Warm up, then wait for device results', 'Change shapes on every call', 'Remove correctness checks'], correctIndex: 1, explanation: 'Warmup separates compilation from execution, and synchronization includes device work in the measurement.' }],
      resources: [{ title: 'Official JAX getting started', url: 'https://docs.jax.dev/en/latest/beginner_guide.html' }, { title: 'JAX installation guide', url: 'https://docs.jax.dev/en/latest/installation.html' }],
    }] }],
  },
  {
    id: 'jev', slug: 'jev', title: 'Jev: Typed Decisions for Agents', description: 'Use TypeSafe AI’s System One model for classification, routing and rubric-based assessment, with measured decision thresholds.', iconName: 'Bot', level: 'Intermediate', accentColor: 'from-purple-500 to-pink-500',
    modules: [{ id: 'jev-decisions', trackId: 'jev', title: 'Decision Design & Evaluation', description: 'Design a decision gate and evaluate it against human labels.', lessons: [{
      id: 'jev-typed-decisions', moduleId: 'jev-decisions', trackId: 'jev', title: 'Jev: Choice, Score and Noul', durationMinutes: 30, difficulty: 'Intermediate', prerequisites: ['API basics', 'Classification metrics'],
      learningObjectives: ['Choose a typed primitive for a decision.', 'Separate independent questions from dependent workflow steps.', 'Evaluate decision quality and choose an escalation threshold.'],
      overview: 'Jev evaluates typed questions against shared state. Use its structured answers to support routing, scoring and verification; validate accuracy on your own workload before automating actions.',
      theory: '### Choose the question type\n\nChoice selects from options; Score assesses a rubric; Noul represents the probability that a statement is true. Choice and Score also expose confidence. Keep each question narrow enough to evaluate one factor.\n\n### Compose the workflow\n\nIndependent questions can be evaluated against the same state in one request. If a later question requires an earlier result, combine results in application code or make a subsequent request. A typed response makes integration simpler but does not guarantee a correct judgment.\n\n### Professional lab: support triage\n\nCreate a labeled set of realistic support tickets with an intent, urgency and expected route. Include ambiguous tickets and out-of-domain examples. Define explicit choices for intent, a documented scoring rubric for severity, and a separate true-or-false question for whether evidence is sufficient. Use the official quickstart for the current API schema; keep credentials in a server-side environment.\n\n### Decide when to abstain\n\nMeasure per-class precision and recall, calibration and review volume on held-out examples. Select a threshold using the cost of incorrect routing and human review. Route missing, invalid or uncertain results to review; log model version and question definitions so you can compare changes. Do not interpret confidence as guaranteed correctness.',
      tradeoffs: ['Narrow questions simplify evaluation but require explicit composition for complex decisions.', 'Higher acceptance thresholds can reduce automatic coverage and increase review load.'], commonMistakes: ['Treating valid output types as proof of correctness.', 'Choosing thresholds without labeled validation data.', 'Putting model API credentials in a public frontend.'],
      interviewQuestions: [{ question: 'How would you validate a Jev routing gate?', answer: 'Compare decisions with held-out human labels, inspect errors by class, measure confidence calibration, and tune an abstention policy before a monitored rollout.' }],
      quiz: [{ id: 'jev-q1', question: 'What should happen when a routing decision is uncertain?', options: ['Always choose the first route', 'Skip logging', 'Apply a validated fallback or human-review policy', 'Assume typed output is correct'], correctIndex: 2, explanation: 'An explicit abstention path limits mistakes when evidence or confidence is insufficient.' }],
      resources: [{ title: 'TypeSafe AI: introduction and quickstart', url: 'https://docs.typesafe.ai/introduction' }],
    }] }],
  },
];
